version: '3.1'

services:

    db:
        image: postgres
        restart: always
        volumes: 
            - ../.dbdata:/var/lib/postgresql/data
        environment:
            TZ: America/Fortaleza
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        
  
    adminer:
        image: adminer
        restart: always
        ports:
        - 8888:8080
